name: Deploy project
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: app
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_KEY }}
          heroku_app_name: "mtstestgo"
          heroku_email: "specforworkwithpeop@gmail.com"
          usedocker: true